Respawn time
transhumandesign/kag-base pull request #1033
Opened 2021-04-17 10:14 UTC by laws65

## Status

- **READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.

## Description

Resolves #746 

## Steps to Test or Reproduce

1. Start a private game
2. Spawn bots in
3. Die and note respawn time

2021-04-17 10:19 UTC, eps0003 requested changes

2021-04-17 10:19 UTC, eps0003 commented on Rules/CTF/Scripts/CTF.as
> +            info.can_spawn_time = respawnTimeSecs * getTicksASecond();
Fix indentation

2021-04-17 10:19 UTC, eps0003 commented on Rules/CTF/Scripts/CTF.as
>  			info.can_spawn_time = ((old_spawn_time > 30) ? old_spawn_time : tickspawndelay);
Remove the old implementation

2021-04-17 10:35 UTC, eps0003 approved these changes

2021-05-04 09:40 UTC, terracraft321 commented
What about the other gamemodes?

2021-05-16 15:16 UTC, Vam-Jam commented
> What about the other gamemodes?

- TTH has far too many issues right now, this change is not suited for it.
- Small CTF uses CTF.as, so it'll use this change.
- TDM does not need this.

2021-05-16 15:17 UTC, Vam-Jam approved these changes

2022-11-12 10:56 UTC, AsuMagic commented
OK, so I did leave that PR hanging for a while but have not addressed the reasons why as I should have.

I generally don't like the magic value and formula approach taken for implementing this.  
It makes it more difficult for people to understand and edit such values, and makes the assumption that we want to scale respawn time linearly with the amount of players, which is not the case.

It would make much more sense to me to explicitly use some threshold and hardcoded respawn time values.  
This would allow configuring the threshold and respawn times through the CTF configuration file as well.

2025-01-23 18:44 UTC, asumagic commented
Closing for inactivity + there hasn't been much demand for it, although we could look in other ways to rebalance low-player count CTF

2025-01-23 18:44 UTC, closed without merging