Sham's UKC 1v1 US knight tournament accolades
transhumandesign/kag-base pull request #1108
Opened 2021-10-22 00:58 UTC by bunniewormy

## Status

- **READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.

## Description

Bracket: https://challonge.com/ukcone

Actual username list:

super_gaming_geek
PUNK123
petgreendino
NoahTheLegend
Wavanardi
Zaniac
teKK1
Appaguchee
Eluded
ShamWow-SuperRag
MHonorM
hankkane
makmoud98
HmmWhyHow
Terracotta
pepasmaga2
hyperkannon
conan2571
HeroBryan
nickkardash

Proof of tournament happening:
[chat-21-09-18-19-04-05.txt](https://github.com/transhumandesign/kag-base/files/7393592/chat-21-09-18-19-04-05.txt)
[chat-21-09-18-19-29-08.txt](https://github.com/transhumandesign/kag-base/files/7393593/chat-21-09-18-19-29-08.txt)
[chat-21-09-18-22-34-12.txt](https://github.com/transhumandesign/kag-base/files/7393594/chat-21-09-18-22-34-12.txt)

2021-10-23 20:30 UTC, AsuMagic submitted a review, later dismissed

2021-11-22 14:16 UTC, bunniewormy commented
- Added sham's UKC 2 tournament: 
https://challonge.com/ukctwo
Custom heads for junko, szwedu, frangeorgeelliott
- Added punk's tournament from this PR https://github.com/transhumandesign/kag-base/pull/1106
- Misc fixes

2021-12-20 23:02 UTC, AsuMagic requested changes

2021-12-20 23:02 UTC, AsuMagic commented on Rules/CommonScripts/accolade_data.cfg
> +	# participation 1 - OCE 1v1 knight tournament for people with no gold medals no. 1
Should be 2

2021-12-20 23:02 UTC, AsuMagic commented on Rules/CommonScripts/accolade_data.cfg
> +	# participation 1 - EU 2v2 archer tournament no. 2
Should also be 2

2021-12-20 23:09 UTC, AsuMagic approved these changes

2021-12-20 23:10 UTC, merged