Add chicken emote; Allow players to sit on eggs to incubate them
transhumandesign/kag-base pull request #1173
Opened 2021-11-24 14:22 UTC by benjamingorman

## Status

- **READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.

## Description

![image](https://user-images.githubusercontent.com/6610341/143255701-f8c96189-a918-4a89-810c-116855ed7d4d.png)

This PR adds a new chicken emote (using one of the existing chicken sprite frames). It also adds the ability for players to sit on eggs to incubate them. An incubated egg will hatch 3x faster than a regular egg.

## Steps to Test or Reproduce

I've tested this locally in sandbox.

- Open sandbox and spawn an egg
- Move over it as knight/builder/archer and crouch
- You should start incubating the egg. Your character will do the chicken emote, and the egg should hatch 3x faster than an un-incubated egg.

2021-11-24 14:27 UTC, benjamingorman commented
The chicken emote is currently on the emote wheel but I notice some of the newer emotes are not so maybe it shouldn't be.

2022-07-03 16:37 UTC, Mazey approved these changes

2022-07-03 16:37 UTC, Mazey commented on Entities/Natural/Animals/Chicken/IncubateEgg.as
> +}
Overall seems good, but please don't forget newline at end of files. Can be merged and done manually though.

2022-07-23 18:10 UTC, AsuMagic requested changes
> The chicken emote is currently on the emote wheel but I notice some of the newer emotes are not so maybe it shouldn't be.

It shouldn't be because the default wheel is already pretty full, and adding the chicken one offsets the up/right/bottom/left pointing emotes.

2023-01-28 19:50 UTC, AsuMagic commented
The PR now conflicts with main if anyone wants to solve this + the issue I mentioned.

2023-02-01 12:31 UTC, benjamingorman commented
I'll update it when I get a chance

2025-01-23 18:43 UTC, asumagic commented
Closing for inactivity + might be superseded by #2141 if it ends up integrating similar changes?

2025-01-23 18:43 UTC, closed without merging