Obstructor and Motion Sensor no longer break background
transhumandesign/kag-base pull request #1243
Opened 2022-04-29 18:36 UTC by mugg91

## Status

- **READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.

## Description

This fixes [issue #592](https://github.com/transhumandesign/kag-base/issues/592).
Background and grass will no longer break when selecting obstructor/sensor and then something else in the build menu.

The same code in DummyOnStatic.as is executed when "selecting obstructor/sensor and then something else" and when the tile actually breaks. So I check the tile's health to make sure the code only executes in the latter case, when the health is 0.

I play-tested the change and the two components behave the same as before.

2022-04-30 13:25 UTC, eps0003 requested changes
I am yet to test in-game.

2022-04-30 13:25 UTC, eps0003 commented on Entities/Structures/Common/DummyOnStatic.as
> +				if (this.getHealth()==0) //this check fixes Obstructor and Sensor breaking background
Be sure to use whitespace around comparison operators.
```suggestion
				if (this.getHealth() == 0) //this check fixes Obstructor and Sensor breaking background
```

2022-04-30 13:25 UTC, eps0003 commented on Entities/Structures/Common/DummyOnStatic.as
> +				if (this.getHealth()==0) //this check fixes Obstructor and Sensor breaking background
Couldn't this be merged with the `else` instead of it being nested inside?

2022-05-16 20:15 UTC, mugg91 commented
I found that both components will remove wood/stone background (if it existed) when getting built.
Obstructor will also remove it whenever goes into background mode.
Not sure if it needs addressing, but it seemed odd.

2023-04-08 22:55 UTC, Gingerbeard5773 approved these changes
Works as intended

2023-04-08 22:55 UTC, Gingerbeard5773 commented on Entities/Structures/Common/DummyOnStatic.as
> +{
tab

2023-04-08 22:55 UTC, Gingerbeard5773 commented on Entities/Structures/Common/DummyOnStatic.as
> +			{
tab

2023-04-09 13:47 UTC, AsuMagic approved these changes

2023-04-09 13:47 UTC, merged