Fireplace that has been there from the start can be extinguished, Fireplace can be set on fire with fire arrow
transhumandesign/kag-base pull request #1244
Opened 2022-04-30 08:23 UTC by mugg91

## Status

- **READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.

## Description

This fixes [issue #1242](https://github.com/transhumandesign/kag-base/issues/1242) and [issue #1206](https://github.com/transhumandesign/kag-base/issues/1206).

Fireplace that has been there from the start - such as the ones in Save the Princess' first map - will now be able to be extinguished by water bomb and water arrow. It was not possible before because with those two (water arrow and water bomb) the game assumed hitter was "water_stun" rather than "water" but fireplace only checked for "water" in onHit().

Fireplace can now be set on fire when shooting fire arrow through them. 
This was done by checking in onCollision() if a blob with fire source is colliding with fireplace.
It works well for the most part. Shooting fire arrow through many fireplaces will ignite all of them most of the time. But shooting from top to bottom may fail sometimes.

I discarded the idea that arrows should have direct collision with fireplace (similar behavior like how vehicles can accept arrow hits) for these reasons: 
* Arrows usually force things to get knocked back, and fireplace is not supposed to get knocked back by an arrow, in my opinion.
* Arrows hitting fireplace would ignite themselves and burn nearby grass/stuff unexpectedly.
* If making it so that arrows despawn when hitting fireplace (so stuff doesn't burn), then shooting arrows through the fireplace to ignite the arrows would not be possible anymore. And I don't want inconsistencies like "turned-off fireplace accepts and despawns fire arrow but turned-on fireplace lets arrows fly through".

Even though fire arrow can't directly hit fireplace, I still added a check "isIgniteHitter" in "onHit()" anyway.

I play-tested and didn't encounter regressions.

## Steps to Test or Reproduce

* Go to Save The Princess, throw water bomb or shoot water arrow at the fireplace at the beginning. Notice it gets extinguished now.
* Extinguish a fireplace and shoot fire arrow through it. Notice that it gets ignited.

2022-04-30 13:21 UTC, eps0003 requested changes
I am yet to test this in-game.

2022-04-30 13:21 UTC, eps0003 commented on Entities/Industry/Fireplace/Fireplace.as
> +	else if (blob !is null && blob.hasTag("fire source")) //fire arrow works
Move the blob null check outside of this if statement so it isn't being repeated by both if statements.

2022-04-30 13:21 UTC, eps0003 commented on Entities/Industry/Fireplace/Fireplace.as
> +	if (isIgniteHitter(customData))
Use `else if` since logically something cannot both extinguish and ignite a fireplace.

2022-05-03 22:13 UTC, mugg91 commented
As said, a fire arrow shot from above the fireplace or from when you stand inside the fireplace, can sometimes miss and not ignite the fireplace. So I added a check to Arrow.as that makes it so that a fire arrow hitting the base of an unlit fireplace will also ignite it.

Just doing SetAnimation("fire") will not properly ignite the fireplace, so I had to copy paste the entire code from fireplace's Ignite(). I didn't manage to find a more clean way. Maybe someone else finds a better way?

2022-05-04 07:51 UTC, eps0003 commented
> Just doing SetAnimation("fire") will not properly ignite the fireplace, so I had to copy paste the entire code from fireplace's Ignite(). I didn't manage to find a more clean way. Maybe someone else finds a better way?

The way to avoid duplicating code in this case is to do the following:

1. Create `FireplaceCommon.as`
2. Create a function like `void IgniteFireplace(CBlob@ blob)` in this file
3. Move the ignite code into this function
4. Use this function in the two places you need to ignite the fireplace

2022-05-04 17:57 UTC, mugg91 commented
Thanks eps, I will consider to change it like you said.

Just want to say, I noticed with the current change, an unlit fireplace will get lit by a lantern. Is this ok or bad? Please say your opinions.

2022-05-05 02:27 UTC, eps0003 commented
> Just want to say, I noticed with the current change, an unlit fireplace will get lit by a lantern. Is this ok or bad? Please say your opinions.

I don't have any opinions on this considering how rare it is to see a fireplace. Feel free to ask others in Discord.

2022-05-06 19:57 UTC, terracraft321 commented
Doesn't sound bad to me

2022-05-28 13:19 UTC, eps0003 submitted a review, later dismissed

2022-05-28 13:19 UTC, eps0003 commented on Entities/Industry/Fireplace/Fireplace.as
>  }
You don't need to wrap `IgniteFireplace` in another function. Just use `IgniteFireplace` directly.

2022-05-28 13:19 UTC, eps0003 commented on Entities/Industry/Fireplace/FireplaceCommon.as
> +	if (this.getSprite().isAnimation("fire")) return;
Add a null check for the sprite just to be safe. And get the sprite once instead of getting it multiple times in this function.

2022-05-28 13:19 UTC, eps0003 commented on Entities/Industry/Fireplace/Fireplace.as
> +	if (blob !is null)
It would be better to change this to an early return to reduce the indentation.

2023-01-28 20:09 UTC, AsuMagic approved these changes

2023-01-28 20:09 UTC, merged