Spawn Sign with your own text in Sandbox
transhumandesign/kag-base pull request #1255
Opened 2022-05-09 16:08 UTC by mugg91

## Status

- **IN DEVELOPMENT**: this PR is still in development, but you would like your changes reviewed.

Will set to "READY" after addressing these:
- Make the game look for bad words in the Sign's text, don't spawn it or censor it.
- Support line breaks with /n like in "TutorialCTF01.as".
- Make sign hittable by builder.

## Description

Before this change, in Sandbox, you could type "!sign" and it spawned a sign saying "The big brown fox jumped over the shaggy chocolate". That's all text you could have. "!sign blah" didn't do anything.

This change makes it so !sign lets you put your own text when spawning a sign in Sandbox.
Type in "!sign your text blah blah $icon$".

https://i.imgur.com/0TFCMoa.png

Let me know what you think.

2022-05-26 00:23 UTC, mugg91 commented
For future reference, the current build lets you spawn crate with a custom description that is not checked for swear words.

So if I or anyone ever do manage to check for swear words in a self-created custom Sign, then Crates might as well get checked, too.

2022-05-28 12:38 UTC, eps0003 requested changes

2022-05-28 12:38 UTC, eps0003 commented on Rules/CommonScripts/ChatCommands.as
> +					createSign(pos, text_in.substr(tokens[0].length+1, -1));
The default value for the second argument is -1 so this line can be simplified to the following:
```suggestion
					createSign(pos, text_in.substr(tokens[0].length + 1));
```

2022-07-03 16:05 UTC, AsuMagic commented
Will conflict with #1210

2022-07-03 17:38 UTC, mugg91 commented
This is currently not anywhere near done and there are issues I ran into that I haven't figured out to fix. It would seem some things are engine-side and cannot be done anyway. Please ignore (or close if you must) this PR for the time being.

2024-01-17 02:04 UTC, closed without merging