[added] Night ambient music
transhumandesign/kag-base pull request #1296
Opened 2022-06-22 17:04 UTC by mugg91

## Status

- **READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.

## Description

Fixes 2) of #1295.

This adds a new night world ambient music track to WARMusic.as and ChallengeMusic.as.
It is crickets chirping which is common to occur at late afternoon to midnight.
This music plays when `getMap().getDayTime()` is between 0.75 and 1.0 - before sunset starts until before dawn starts.

The music used is the first 45 seconds of this, amplied by +6.1 and saved as .ogg at quality level 6. It is free-to-use: 
https://pixabay.com/sound-effects/cricket-sound-14867/
If you think there is a better soundtrack, let me know.

## Steps to Test or Reproduce

Go to Sandbox or TTH tutorial.
Wait until sunset and night (or type `getMap().SetDayTime(0.7f);` in console to jump right before a sunset).
Notice the night ambient music.

2022-07-03 16:11 UTC, AsuMagic requested changes
The background music really doesn't fit, you can easily hear city sounds and cars running. :P

2022-07-03 17:10 UTC, mugg91 commented
> The background music really doesn't fit, you can easily hear city sounds and cars running. :P

Please note, only the first 45 seconds are used. The part of the car driving is not included.
Any other sound effects are basicly inaudible in actual gameplay (note, there is the game music running on top of this) and could be assumed to be village sounds or wind.

2022-07-23 19:01 UTC, AsuMagic requested changes

2022-07-23 19:01 UTC, AsuMagic commented on Entities/Meta/ChallengeMusic.as
> +				|| mixer.isPlaying(world_ambient_mountain
Missing `)`, this causes a syntax error.

2022-07-23 19:01 UTC, AsuMagic commented on Entities/Meta/ChallengeMusic.as
> +		bool isNight = map.getDayTime() > 0.75f;
This seems to be a generally poor value. `>0.85 && <0.1` would probably be more fitting with the current sky gradient.

2022-07-23 20:04 UTC, AsuMagic submitted a review, later dismissed

2022-07-23 20:04 UTC, AsuMagic commented on Entities/Meta/ChallengeMusic.as
> +		bool isNight = map.getDayTime() > 0.75f;
```suggestion
		bool isNight = map.getDayTime() > 0.85f && map.getDayTime() < 0.1f;
```
I have now realized that fix suggestions are a thing.

2022-07-23 20:04 UTC, AsuMagic commented on Entities/Meta/ChallengeMusic.as
> +				|| mixer.isPlaying(world_ambient_mountain
```suggestion
				|| mixer.isPlaying(world_ambient_mountain)
```

2022-07-23 20:04 UTC, AsuMagic approved these changes

2022-07-23 20:06 UTC, merged