[fixed] picking up items after getting in a crate
transhumandesign/kag-base pull request #1332
Opened 2022-07-24 17:17 UTC by mugg91

## Status

- **READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.

## Description

Fixes #1320.

At high ping in online, you could pick up items after sending the "get in" command but before you got put in the crate.
This PR makes it so `onCommand()` in StandardControls.as checks if the picker is in inventory. If yes, the picking up will not happen.

## Steps to Test or Reproduce

Go to a high ping server.
Have a crate in hand and keep showing buttons.
While showing buttons, throw the crate aside.
Be near the crate or any item and click on the "get in" button and then press "pick up" in quick succession.
The crate (or other item) will be picked up while you are inside the crate.

**After this change, you will get inside the crate and the pickup will not happen.**

2022-07-25 16:22 UTC, mugg91 commented
We should consider adding another check `!pick.hasAttached())` because it could be possible someone sits in a Dinghy that is about to be picked up.

2022-11-26 15:53 UTC, mugg91 commented
The issue I brought up in my previous comment actually existed ( #1519 ) so I made a commit that will fix it.

Reproduction Steps:

1) Add this hack to `Lantern.as onTick()`:
```
	CBlob@ b = getBlobByName("archer");
	CBlob@ d = getBlobByName("dinghy");
	if (b !is null && d !is null && isServer())
	{
		if (getGameTime() % 140 == 0)
		{
			if(!d.isAttached())
				d.server_AttachTo(b, "ROWER");
			
		}
		else if (getGameTime() % 140 == 100)
		{
			b.server_DetachFromAll();
		}
	}
```
2) Remove `this.getCurrentScript().runFlags |= Script::tick_inwater;` from `Lantern.as`.
3) Run [clumsy](http://jagt.github.io/clumsy/) to simulate 300 ping.
4) Run `dedicatedserver.bat` and join it.
5) Spawn `!dinghy`, `!archer` and `!lantern`.
6) The archer will now repeatedly get in and out of Dinghy. Try to pick up the Dinghy at the same time the archer gets in.

You will notice, before commit [c73b3b1](https://github.com/transhumandesign/kag-base/pull/1332/commits/c73b3b1331a7f35bb0e10cc25c675b573992eab4) it's possible to do it easily. But it will never happen after [c73b3b1](https://github.com/transhumandesign/kag-base/pull/1332/commits/c73b3b1331a7f35bb0e10cc25c675b573992eab4).

2023-01-30 13:19 UTC, Gingerbeard5773 requested changes

2023-01-30 13:19 UTC, Gingerbeard5773 commented on Entities/Common/Controls/StandardControls.as
> +		    && !pick.hasAttached())
!pick.hasAttached() could potentially mess with some mods, so instead use pick.canBePickedUp(). This still works the same with the dinghy.
```suggestion
		    && pick.canBePickedUp(owner))
```

2023-01-30 13:27 UTC, AsuMagic approved these changes

2023-01-30 13:27 UTC, merged