Fixed seed placement bug.
transhumandesign/kag-base pull request #1533
Opened 2022-12-13 00:13 UTC by Hobey

## Status
- **READY**
- I have only tested locally.
- I have NOT tested multiplayer on a server.

## Description
Resolves #1514.
See comments in [BuilderLogic.as (line 657)](https://github.com/Hobey/kag-base/blob/4c9786c7a95aaac49aa796da5a5ecdd2abf144b5/Entities/Characters/Builder/BuilderLogic.as#L657)

## Steps to Test or Reproduce
- Put a (tree) seed in your inventory; (e.g. do "!tree_pine", then kill tree)
- Then you start building blobs (e.g. doors) until you run out ot mats for that blob;
- Then you take the seed out of your inventory
- Then you try to place the seed but you can't because you get a "Requires 30 wood" message;

## Some useful information

git branch used:  seed_fix
https://github.com/Hobey/kag-base/tree/seed_fix

2022-12-13 09:31 UTC, eps0003 requested changes

2022-12-13 09:31 UTC, eps0003 commented on Entities/Characters/Builder/BuilderLogic.as
> +	if (attached.getName().getHash() == 1346747564) // (attached.getName() == "seed")
There is no need to optimise this by comparing the hash. Just compare the name and combine the two `if` statements into one.

2022-12-13 09:31 UTC, eps0003 commented on Entities/Characters/Builder/BuilderLogic.as
> +		// https://youtu.be/ie7KtTIHEvQ [Fix, but without the 'if' that filters for "seed" blobs only]
Too many comments for a one-line fix. Shorten the comment down to one or two lines max.

2022-12-13 09:33 UTC, eps0003 commented
Please test on a local dedicated server rather than just localhost. Ask in Discord if you are unsure how to do this.

2022-12-13 17:30 UTC, Hobey commented
Did testing on a server with trollbird just now. Fix seems to work. PR is ready now.

2023-01-03 14:57 UTC, AsuMagic commented
Bit of a painful workaround :P

I'm not even sure what code in the first place allows seed placement. Would be worth checking if there is a more generic fix to it.

2023-01-06 07:40 UTC, Gingerbeard5773 commented
There is a more straight forward solution that could be done in BlobPlacement.as at line 298. Add a check to make sure we are using correct requirements for the the carried blob. It would look something like
``if (block !is null && block.name == carryBlob.getName())``
this approach is a lot smarter because we aren't hardcoding the seed's name into the code, and will work for any theoretical blob that can be placed like the seed. Also its a one line fix for this bug. BTW I haven't tested this code extensively... do your own testing if you use this method. @Hobey @AsuMagic

2023-01-28 13:07 UTC, closed without merging