Revised TDM maps
transhumandesign/kag-base pull request #1702
Opened 2023-10-05 23:02 UTC by NoahTheLegend

removed Noah_ShadedCitadel from mapcycle (too vertical, doesnt really feel enjoyable)
changed mostly cosmetically 3 other my maps, changed moveset on them (added more strategic positions, less OP offensive ledges, more flatness etc)
fixed Vans_Ziraeth_v2, removed gold from top that may be the reason of crashes

2024-09-18 16:01 UTC, Vam-Jam requested changes
Remove the fix for Vans_Ziraeth_v2

2025-09-24 22:01 UTC, NoahTheLegend commented
> Remove the fix for Vans_Ziraeth_v2

regarding to the request, was that already fixed in engine?

2025-09-25 08:05 UTC, Vam-Jam commented
> > Remove the fix for Vans_Ziraeth_v2
> 
> regarding to the request, was that already fixed in engine?

In vanilla, yea, in staging it was already fixed iirc(?). If it happens in staging we can port the fix over.

2025-09-25 09:38 UTC, NoahTheLegend commented
Anyway, i rolled back the commit with ziraeth map fix, perhaps you can merge it now.

2026-01-18 10:50 UTC, NoahTheLegend commented
closing as waffle is now leading another pr

2026-01-18 10:50 UTC, closed without merging