Emote error fix
transhumandesign/kag-base pull request #1703
Opened 2023-10-08 03:45 UTC by S-Numan

## Status

- **READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.

## Description

If EmoteMenu.as is not in the gamemode.cfg, when a player spawns as a blob, it errors.
The EmoteMenu.as script, calls the function `LoadEmotes(rules, cfg)`, inside of which sets `this.set("emotes", @emotesDict);`
If EmoteMenu.as is not in gamemode.cfg, then the rules "emotes" is null.

In a player's blob, the script EmoteHotkeys.as, calls readEmoteBindings in onInit()
In that function, this happens `getRules().get("emotes", @emotes);`
Then it promptly uses the variable emotes, which may be null. Hence, the error.

This edit simply halts getting emotebinds if EmoteMenu.as isn't in rules.
It halts in onTick if the size of emotebinds was 0.
This is done after "reload emotes", so one could possibly add EmoteMenu.as afterwards, tag rules with "reload emotes", and have it reload and work normally without extra fuss.

## Steps to Test or Reproduce

Play a gamemode without EmoteMenu.as in the script list. Spawn as a blob that has the script EmoteHotkeys.as

2024-09-18 15:52 UTC, Vam-Jam requested changes

2024-09-18 15:52 UTC, Vam-Jam commented on Entities/Common/Emotes/EmoteHotkeys.as
> +
Fix the indent, otherwise this looks good to me

2024-12-14 17:08 UTC, asumagic commented on Entities/Common/Emotes/EmoteHotkeys.as
> +
```suggestion
	//Stop if there is no emote menu.
	if(!getRules().hasScript("EmoteMenu.as"))
	{
		return;
	}

```

2024-12-14 17:09 UTC, asumagic approved these changes

2024-12-14 17:09 UTC, merged