Scripted playernames.
transhumandesign/kag-base pull request #1761
Opened 2023-12-15 14:16 UTC by GoldenGuy

## Status

- **READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game. But can still be tweaked if something interesting is suggested.

## Description

Moves player names and hearts ui from engine to scripts. Also added fade-in behavior.
Along with this pr there should be an engine pr to remove names from engine.

## Steps to Test or Reproduce

1) join server/sinlgeplayer
2) spawn bots
3) see this:

https://github.com/transhumandesign/kag-base/assets/26719582/44094844-4805-4258-a36c-19d332a0ee23

https://github.com/transhumandesign/kag-base/assets/26719582/49160f41-c2cd-4f9b-bf39-78aa22b06200

2023-12-15 15:16 UTC, GoldenGuy commented
added clantags (forgor)
![image](https://github.com/transhumandesign/kag-base/assets/26719582/dc3c83cf-0dcd-4b55-be61-c3ffa981161e)

2024-02-18 11:47 UTC, mugg91 commented
I have no tested it yet, but I guess with this we can now work on these:
https://github.com/transhumandesign/kag-base/issues/1541
https://github.com/transhumandesign/kag-base/issues/1377
https://github.com/transhumandesign/kag-base/issues/1098

2024-02-25 09:03 UTC, GELGELAT commented
make it possible to disable it in the settings, I personally want to see nicknames always

2024-09-03 14:24 UTC, Vam-Jam submitted a review, later dismissed
LGTM, this will break mods. 

If we decide to automatically fix this for modders (and how) is up for debate

2024-09-03 14:26 UTC, Gingerbeard5773 approved these changes

2024-09-03 14:26 UTC, Gingerbeard5773 commented on Rules/CommonScripts/PlayerNames.as
> +		if (blob !is null) // you never know...
could put a continue here to make it sleeker

2024-09-03 14:26 UTC, Gingerbeard5773 commented on Rules/CommonScripts/PlayerNames.as
> +			if (player !is null) // you never know...
here too

2024-10-12 02:34 UTC, Gingerbeard5773 requested changes

2024-10-12 02:34 UTC, Gingerbeard5773 commented on Rules/CommonScripts/PlayerNames.as
> +		CPlayer@ player = getPlayer(i);
because of an engine bug, player can be null here if someone gets kicked from the server- add a null check

2024-10-24 10:02 UTC, Gingerbeard5773 commented
closes #282

2024-12-14 16:21 UTC, asumagic commented
Probably should add a darkness check (otherwise you can scan for people underground). Will look into it.
This was broken on staging IIRC on the engine hardcoded way of things.

`getColorLight` on staging no longer gets influenced by lanterns but there's no way around this (for now).

2024-12-14 16:46 UTC, asumagic approved these changes
Tested on dedi, made some changes to better match past behavior

2024-12-14 16:46 UTC, merged