[added] Two new components: Bell & Display
transhumandesign/kag-base pull request #2008
Opened 2024-04-12 11:34 UTC by mugg91

## Status

- **READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.

## Description
```
[added] Load component Bell
[added] Passive component Display
```
This PR adds two new components.
They will probably not see uses in TDM, but will possibly be enjoyed by Sandbox players.
Feel free to suggest changes.

## Bell
Will ring when powered.
Free sound taken from here: https://pixabay.com/sound-effects/ac-bel-105874/

Sprite ticking performance is good.
I checked with `for (int i = 0; i < 10000; i++)` loop around the code that sets offset and rotation of bell spritelayer and ringer spritelayer. With one Bell it is barely noticeable while with two, there is quite a bit of lag. 
This result is satisfactory, because it means it takes 10000 Bells before there is lag just from the ticking. In reality lag starts happening when there are like 300~400 blobs just existing.

![bell](https://github.com/transhumandesign/kag-base/assets/14877281/a99bcff4-6682-452a-80d3-b39003baed9e)

## Display
Will work like a junction that displays the current power number.
While it is possible to use `g_debug = 1` in console to display power numbers, I would like an in-game way of showing it.

It can display from `0` up to `16`, higher values will display `Er`, standing for "Error". In actual game-play, only `9` can be reached since power sources are coded to start with power `10`.

![screen-24-04-12-10-38-55](https://github.com/transhumandesign/kag-base/assets/14877281/0e2eeab5-0474-4afc-b253-8038b2d64f12)

2024-04-13 23:34 UTC, mugg91 commented
@NoahTheLegend 
Thanks for your advice. Although I think the color contrast is ok. I'm afraid making it fully black will look odd although it would be possible to give it a dark grey outline.

That being said, I added a commit that makes improvements to how Bell looks and animates.

2024-09-03 13:43 UTC, Vam-Jam requested changes
It seems to work from my testing (I can not test the audio since linux).

When placing the bell, the blob appears to be semi broken.

![](https://fs.vamist.dev/4da755-M2OtJNCxRrNkdhtp.png)

I'm unsure about the screen's colour, it does look out of place.

2024-10-15 03:23 UTC, mugg91 commented
@Vam-Jam 
Do you mean the sprite for Bell looks odd when placing it?
I didn't change since since Lever also uses half its sprite when placing it.

2024-10-15 05:25 UTC, Vam-Jam commented
> @Vam-Jam Do you mean the sprite for Bell looks odd when placing it? I didn't change it back then since Lever also uses half its sprite when placing it.

Yea, if that's the case I'll revisit it this week.

2026-01-17 23:52 UTC, Vam-Jam commented
Closing as this is more suited for a sandbox mod

2026-01-17 23:52 UTC, closed without merging