[added] new source component: Solar Panel
transhumandesign/kag-base pull request #2014
Opened 2024-04-15 09:53 UTC by mugg91

## Status

- **IN DEVELOPMENT**: this PR is still in development, but you would like your changes reviewed.
- Doesn't work on server right now
- Blob light not taken into account yet

## Description
```
[added] Solar Panel
```

This PR adds Solar Panel as a new Source component.
It will provide power based on tile light of the tile it's placed on. At full light (255) it provides the full power source (10) whereas less light will provide less power accordingly.

Because of an issue where dark areas can randomly gain light ( https://github.com/transhumandesign/kag-base/issues/2013 ), solar panel would start running randomly even in dark areas. So I added logic to make it first tick 5 times every 45th tick to see if light continues to exist. In dark areas the random light would usually die out after about 2-3 seconds. Therefore, Solar Panel will start providing light after a few seconds of it existing in light.

Solar Panel's tick frequency is 45 when it currently hasn't received enough light to start running (= provide power), and 3 when it has enough light and is running.

Blob emitted light is apparently treated separately from tile map light so Solar Panel can't be powered by a lamp in a dark area right now. Maybe I will add more logic to take blob light into account as well. If so, then a Lamp getting powered with only a power level of 1 or 2 shouldn't provide full light but only reduced light. Solar Panel getting powered by a lamp that it powers itself would be kind of stupid. Or it would be a silly KAG logic?

Not sure how this could be supported in the future if light is going to change ( https://github.com/transhumandesign/kag-base/issues/2013#issuecomment-2056282524 ).

Currently only works in offline because tile light doesn't exist on server so light will always be 0 there. I have had no luck with fixing it so far, but I will keep trying.

## Screenshots
![screen-24-04-15-10-56-39](https://github.com/transhumandesign/kag-base/assets/14877281/08220061-56dc-472a-ac6d-fe88599240d8)
![screen-24-04-15-10-56-57](https://github.com/transhumandesign/kag-base/assets/14877281/fc149d53-9712-406d-bc0e-d6d1b6b44045)
![screen-24-04-15-11-00-08](https://github.com/transhumandesign/kag-base/assets/14877281/58b645c9-17d4-44ef-9b26-b8acc766f138)
![screen-24-04-15-10-59-35](https://github.com/transhumandesign/kag-base/assets/14877281/e29f8e33-947f-4693-96e1-3a7c9118418d)

2024-09-03 12:51 UTC, Vam-Jam requested changes
Does not function correctly on a dedicated server, seems to just output at max power all the time regardless of the brightness

2024-10-15 03:26 UTC, mugg91 commented
Hmm, it also doesn't work in offline. Not sure what went wrong, since it did work at one point.
I'm not submitting PRs unless I'm convinced they are complete.

I will take a look.

2026-01-17 23:50 UTC, Vam-Jam commented
Closing as this is better suited for mods

2026-01-17 23:50 UTC, closed without merging

2026-01-18 22:05 UTC, mugg91 commented
With the game featuring day & night, this makes sense to me to put in the game. Sad about the decision, but as explained, it is not possible to implement it anyway due to `getLuminance()` always returning 255 on server.