[fix] fix stun, when you jumping on trampoline
transhumandesign/kag-base pull request #2063
Opened 2024-05-04 17:46 UTC by TerminalHash

## Status

- **READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.

## Description

In the standard situation, when trying to jump on a trampoline for a while, the player gets a stun:
https://github.com/transhumandesign/kag-base/assets/64691722/5728a98d-23bc-4a13-99f9-62967c078928

With the fix, the player will no longer get stun from jumping on the trampoline (including from a lower height)
https://github.com/transhumandesign/kag-base/assets/64691722/22156bef-395f-4181-9d91-003d8e8e8a47

## Steps to Test or Reproduce
1. Build a small pillar of blocks upwards
2. Put the trampoline underneath
3. Climb the pole and jump from it onto the trampoline
4. ...
5. STUN!

2024-09-03 08:52 UTC, Vam-Jam requested changes
Format the if statement to match, otherwise the code works fine and not found any bugs

2024-09-03 08:52 UTC, Vam-Jam commented on Entities/Common/Movement/FallDamage.as
> +				if (b is null) continue;
You wont need a null check here, all the blobs returned by getBlobsInRadius are valid (and you are not storing it over multiple ticks)

2024-09-03 09:58 UTC, TerminalHash commented
done

2024-09-03 13:17 UTC, Vam-Jam submitted a review, later dismissed
lgtm

2024-09-06 08:37 UTC, Vam-Jam approved these changes

2025-01-21 21:59 UTC, asumagic approved these changes
This is very imperfect because it will cancel fall damage even in cases where it shouldn't (most notably when holding crouch while falling down), but I will merge this as is despite this. IMO it's less of a big deal than trampolines being basically broken half the time.

2025-01-21 21:59 UTC, merged