Builder Queued Hit Fix
transhumandesign/kag-base pull request #2069
Opened 2024-05-13 04:12 UTC by mehwaffle10

## Status

- **READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.

## Description
New logic for queued hits in BuilderLogic.as does not function, causing builders to periodically not break blocks. 

Safe reading a CBitStream after the onCommand hook fails, always reading the values in onCommand and caching them instead of the CBitStream fixes the issue.

Mentioned in issue https://github.com/transhumandesign/kag-base/issues/2065

## Steps to Test or Reproduce
1. Swap to builder
2. Continually break blocks until a swing does not register

2024-06-04 07:48 UTC, mugg91 commented
When is this going to get implemented?
The pickaxe missing every 3rd hit is serious. I was under the impression a hotfix was going to be released soon.

2024-09-02 17:29 UTC, Vam-Jam requested changes
PR functions correctly, no longer skipping random hits. Has been tested by other people in CTF servers.

Fix indents, otherwise it looks good

2024-09-11 08:18 UTC, Vam-Jam approved these changes

2024-12-09 21:13 UTC, asumagic approved these changes

2024-12-09 21:13 UTC, merged