[fixed] You no longer can take fall damage twice on the same tick
transhumandesign/kag-base pull request #2185
Opened 2024-11-24 18:47 UTC by mugg91

## Status

- **READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.

## Description

```
[fixed] You no longer can take fall damage twice on the same tick
```

Fixes https://github.com/transhumandesign/kag-base/issues/2183

When applying the fall damage hit in `FallDamage.as`, the game time is saved to the blob.
At the beginning of `onCollision()` the code drops out if it detects that it's the same tick again so it doesn't apply the hit twice.

I'm not sure why it happens in the first place. This is just a simple fix I came up with. Of course it could be worth looking for the root of the problem.

Tested in offline and online, works correctly. 

## Reproduction
Build a construction like in the screenshot from the issue linked above.
You have to be standing on a corner with the block being on your left or right side of the character.
When getting bounced down, you are taking two hits for 1 heart of total damage. **After this PR, it is only one hit for a total of 0.5 hearts damage**

2024-11-24 19:02 UTC, Vam-Jam commented
> I'm not sure why it happens in the first place

It's to do with box2d, each tile is made up of segments, on a corner, you can touch two segments, so the onCollision hook gets called twice since the game reports you touched two different segments at fast enough speeds.

2024-11-24 19:06 UTC, Vam-Jam requested changes

2024-11-24 19:06 UTC, Vam-Jam commented on Entities/Common/Movement/FallDamage.as
> +				this.set_u16("last fall hit", getGameTime()); // fixes bug of this code running twice in the same tick
getGameTime() returns a u32, not a u16.

2025-01-22 00:32 UTC, asumagic approved these changes
The approach seems sound enough to me. I was thinking of possible edge cases where it would be possible for fall damage to actually need to be applied twice within the same tick (e.g. fast collision with some tile, then sliding off and hitting something again?), but I'm not sure this even ever happens in practice.

2025-01-22 00:33 UTC, merged