[fixed] mechanisms
transhumandesign/kag-base pull request #2219
Opened 2024-12-03 03:13 UTC by Gingerbeard5773

## Status

- **READY**:

## Description

Mechanisms have been left behind with every update, causing various bugs.

* Fixes mechanism states & appearance not synchronizing to joining players on dedi.
* Fixes mechanism effects not appearing on client (lever & button).
* Fixes a problem where mechanism code was executed twice on localhost.
* Fixes a bug where players could not input items into the magazine due to their resolution.
* Improves the magazine so that it is easier to use.
* Fixed blood not appearing on the spiker.
* Improves the obstructor by giving it damage frames.
* Deletes two legacy files that become unnecessary with this PR. Don't scream at me for it because I genuinely believe it wont cause any problems for modders.

resolves #1274
resolves #1874
resolves #1875
resolves #2004
resolves #2152
resolves #2201
resolves #2200

Other PRs that are also closed by default due to this PR 
#1879
#2007
#2202

2024-12-09 11:12 UTC, Vam-Jam requested changes
Dispensers can not be placed in sandbox or by the map loader. Results in TDM maps breaking

![](https://fs.vamist.dev/709659-YEDdws1Bppp8WtVh.png)

2024-12-10 01:26 UTC, Gingerbeard5773 commented
> Dispensers can not be placed in sandbox or by the map loader. Results in TDM maps breaking
resolved

2024-12-10 12:00 UTC, Vam-Jam commented on Entities/Structures/Components/Load/Dispenser/Dispenser.as
>  			getMap().getBlobsAtPosition((offset * -1) * 8 + position, @blobs);
use map instead of getMap() here

2024-12-10 12:02 UTC, Vam-Jam submitted a review, later dismissed
I played through a few TDM rounds, maps seem to be working correctly now, things worked when testing in sandbox. May need more testing but LGTM

2024-12-11 08:06 UTC, Vam-Jam approved these changes

2024-12-14 18:52 UTC, asumagic approved these changes
Also tested a bit manually in sandbox on dedi + tested TDM maps on dedi, saw nothing abnormal.

2024-12-14 18:52 UTC, merged

2024-12-17 21:43 UTC, mugg91 commented
Spiker seems to behave normally now, in both offline and online.
The only thing I found is that Lever will already by activated when placed; previously it was in deactivated state when placed.

2024-12-22 09:02 UTC, mugg91 commented
Just for future reference, this PR made it so that Obstructor and Sensor can't be built hanging from a row of blocks anymore.
It was more like a bug than a feature, so it is fine.