[Changes] Trampoline can now rotate 360 like drill
transhumandesign/kag-base pull request #796
Opened 2020-05-09 21:33 UTC by Vam-Jam

Code done by @CatWiz, asked me to make a PR for him

**Key features**
- Trampolines now follow the mouse in 360 degree, like drill does
- Press ctrl to revert back to 45 degree lock like before

2020-05-09 21:40 UTC, andreyrk commented
Does this actually affect the direction of impulse?

2020-05-09 21:43 UTC, bunniewormy commented
One issue is that you can't actually drop a trampoline at the angle you want (for example to put a trampoline on top of tower between some blocks), even when holding CTRL.

2020-05-10 09:55 UTC, AsuMagic commented
I think we probably should have new engine-side keybindings for these since it is not explained anywhere or intuitive at all that the ctrl key is useful for that (and even then you'd have to look into the bindings again to figure this out).

Would a E bubble button make more sense maybe?

2020-05-10 11:47 UTC, andreyrk commented
Ideally I think it would be better to not have an additional key for that and leave it as default. But I don't know what effect that would have on gameplay mechanics as to which people are used to

2020-09-28 17:09 UTC, eps0003 requested changes

2020-09-28 17:09 UTC, eps0003 commented on Entities/Structures/Trampoline/TrampolineLogic.as
> +	if (controls.isKeyPressed(KEY_LCONTROL))
Any reason why you chose ctrl over shift?
I think you should use `AK_BUILD_MODIFIER` which is bound to ctrl by default and is bindable.
```suggestion
	if (controls.isKeyPressed(AK_BUILD_MODIFIER))
```

2020-09-28 17:09 UTC, eps0003 commented on Entities/Structures/Trampoline/TrampolineLogic.as
> +		this.setAngleDegrees(-angle+90);
The trampoline spazzes out if you move your cursor to the centre point of rotation. There should be a threshold at which it stops updating its angle if the cursor is too close.

2020-10-14 03:55 UTC, eps0003 commented
The snapped rotation while holding ctrl is only visible client-side.

2020-10-14 04:11 UTC, eps0003 commented on Entities/Structures/Trampoline/TrampolineLogic.as
> +		}
I think the snapped rotation should work in all 8 directions
```suggestion
		angle = Maths::Floor((angle + 22.5f) / 45) * 45;
```

2020-11-18 13:31 UTC, Vam-Jam commented
Closed - @CatWiz request

2020-11-18 13:31 UTC, closed without merging