Blobs recheck their collision with player after they crouched
transhumandesign/kag-base pull request #907
Opened 2020-09-20 17:15 UTC by CatWiz

## Status

- **READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.

## Description

Crouching makes blobs that are touching player blob recheck their collisions with it. Fixes problem when crouching doesnt do anything if enemy keeps walking into you after touching you/is standing on you.

2020-09-20 17:27 UTC, eps0003 commented
You should also do the same when a player dies. I've had situations where I cannot walk past a dead body because I killed them while colliding with them.

2020-09-20 17:32 UTC, CatWiz commented
RunnerDeath already does checkCollisionsAgain for the body. Should it make all blobs that are touching it recheck their collisions instead?

2020-09-23 10:19 UTC, eps0003 commented
Not sure what needs to be done to fix it. I just wanted to make it known that similar behaviour occurs with dead bodies.

2020-10-01 09:55 UTC, eps0003 requested changes

2020-10-01 09:55 UTC, eps0003 commented on Entities/Characters/Scripts/CrouchCommon.as
> +	&& !this.hasTag("prevent crouch");
There's no need to repeat the same chunk of code
```suggestion
	return isCrouching(this) && this.isKeyJustPressed(key_down);
```

2020-10-07 03:15 UTC, merged