Saplings and gold that falls in the void reappears at the top of the map.
transhumandesign/kag-base pull request #991
Opened 2020-12-23 07:03 UTC by Hobey

- **READY**   (tested on modded CTF server)

[Demo](https://user-images.githubusercontent.com/26771587/102968642-89d3cc00-44f4-11eb-8b48-f61729defa22.mp4)

Destroying enemy gold and saplings is sometimes fun to do and sometimes it's fun to counterplay.
Sometimes I find though that gold and saplings should be an **actually permanent** resource.

Definitely a mixed opinion change. Personally I would prefer gold and saplings to be permanent.

2020-12-23 11:37 UTC, CatWiz commented
Does it preserve item's momentum? Looks like it doesn't. Maybe it should.

2020-12-23 11:43 UTC, Hobey commented
I doesn't preserve momentum atm; the blob actually dies and that's what I'm using to detect that it fell in the void, and I just create a copy of the blob at the top of the map at the same x coordinate; definitely could just set the velocity (would make it feel way more toroidal!) 

dunno if there's maybe a way to keep a blob alive from inside of onDie(); that would preserve all properties (which doesn't really matter, but would be nice; also would be computationally cheaper probably)

2020-12-25 03:13 UTC, eps0003 requested changes

2020-12-25 03:13 UTC, eps0003 commented on Entities/Materials/Construction/MaterialGold.as
> +            if (!blob.hasTag("merge_killed")) {
Merge these three if statements into one

2020-12-25 03:13 UTC, eps0003 commented on Entities/Materials/Construction/MaterialGold.as
> +                float max_x = (map.tilemapwidth * map.tilesize - 16);
Shouldn't you instead use the blob's radius instead of constants?

2020-12-25 03:13 UTC, eps0003 commented on Entities/Materials/Construction/MaterialGold.as
> +                while (true) {
Why not use a for loop? Infinite while loops are scary!

2020-12-25 03:13 UTC, eps0003 commented on Entities/Materials/Construction/MaterialGold.as
> +                        do_summon = false; // NOTE(hobey): if the blob fell into the void, and there's a colomn of blocks from top to bottom of the map, delete the blob for good
Maybe instead of deleting the blob, you instead search horizontally outwards for a valid position.

2020-12-25 03:13 UTC, eps0003 commented on Entities/Natural/Seed/Seed.as
> +void onDie (CBlob@ blob) {
You're pretty much repeating the exact same code as in the other file. Figure out a way to reuse most of this code.

2020-12-26 08:51 UTC, Hobey commented
I'm won't edit this branch; I'm exhausted.

2021-02-18 04:59 UTC, Harrison-Miller commented
1. Should probably find the nearest ground to spawn it over, because it may just keep looping over the void.
2. What happens if a player has gold in their inventory and voids out.

2021-08-19 10:06 UTC, Hobey commented
Closing this branch since the meaning of gold will probably change significantly through the changes of CTF Rebuild. 

I might revisit this idea if gold-permanence ends up being a thing people want, but then it would be implemented with parachute crates, or a bird bringing the gold back out of the void, or some continuous natural regeneration of gold in the map up to a certain limit.

2021-08-19 10:06 UTC, closed without merging